import { createGroundedResourceSkill, mapGroundedMarkdownToNotePreview } from './resourceSkillFactory.js';

export const fileSkills = Object.freeze([
  createGroundedResourceSkill({
    id: 'file.summarize',
    domain: 'file',
    resourceTypes: ['file'],
    minResources: 1,
    maxResources: 1,
    taskLabel: '总结当前文件',
    defaultInstruction: '提炼文档主旨、结构、关键事实、结论和行动项。',
    systemRole: '你是轻笺文件模块的文档总结 Skill。',
    historyTurns: 0,
  }),
  createGroundedResourceSkill({
    id: 'file.ask',
    domain: 'file',
    resourceTypes: ['file'],
    minResources: 1,
    maxResources: 1,
    taskLabel: '回答关于当前文件的问题',
    defaultInstruction: '直接回答问题，并指出证据位置与覆盖限制。',
    systemRole: '你是轻笺文件模块的文档问答 Skill。',
    questionRequired: true,
    historyTurns: 5,
  }),
  createGroundedResourceSkill({
    id: 'file.compare',
    domain: 'file',
    resourceTypes: ['file'],
    minResources: 2,
    maxResources: 5,
    taskLabel: '比较所选文件',
    defaultInstruction: '比较各文件的共同点、差异、冲突、版本变化与可合并信息。',
    systemRole: '你是轻笺文件模块的多文档比较 Skill。',
    historyTurns: 0,
  }),
  createGroundedResourceSkill({
    id: 'file.create_note_preview',
    domain: 'file',
    resourceTypes: ['file'],
    minResources: 1,
    maxResources: 5,
    taskLabel: '根据所选文件生成笔记草稿',
    defaultInstruction: '生成保留来源引用的结构化 Markdown 笔记草稿。',
    systemRole: '你是轻笺文件模块的文档转笔记 Skill。',
    effect: 'preview',
    availableActions: [{ id: 'create_note_from_preview', label: '在笔记编辑器中继续', requiresConfirmation: true }],
    mapResult: mapGroundedMarkdownToNotePreview,
    modelPolicy: { temperature: 0.3, maxTokens: 6000 },
  }),
]);
