/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/base/PageResponse/403.vue')['default']
    404: typeof import('./src/components/base/PageResponse/404.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BAlert: typeof import('./src/components/base/BasicComponents/BModal/BAlert.vue')['default']
    BButton: typeof import('./src/components/base/BasicComponents/BButton.vue')['default']
    BCard: typeof import('./src/components/base/BasicComponents/BCard.vue')['default']
    BCheckbox: typeof import('./src/components/base/BasicComponents/BCheckbox.vue')['default']
    BFilterDropdown: typeof import('./src/components/base/BasicComponents/BFilterDropdown.vue')['default']
    BForm: typeof import('./src/components/base/BasicComponents/BForm/BForm.vue')['default']
    BInput: typeof import('./src/components/base/BasicComponents/BInput.vue')['default']
    BList: typeof import('./src/components/base/BasicComponents/BList.vue')['default']
    BLoading: typeof import('./src/components/base/BasicComponents/BLoading.vue')['default']
    BMenu: typeof import('./src/components/base/BasicComponents/BMenu.vue')['default']
    BModal: typeof import('./src/components/base/BasicComponents/BModal/BModal.vue')['default']
    BRadio: typeof import('./src/components/base/BasicComponents/BRadio.vue')['default']
    BSelect: typeof import('./src/components/base/BasicComponents/BSelect.vue')['default']
    BSpace: typeof import('./src/components/base/BasicComponents/BSpace.vue')['default']
    BTable: typeof import('./src/components/base/BasicComponents/BTable/BTable.vue')['default']
    BTabs: typeof import('./src/components/base/BasicComponents/BTabs.vue')['default']
    BTree: typeof import('./src/components/base/BasicComponents/BTree.vue')['default']
    BUpload: typeof import('./src/components/base/BasicComponents/BUpload.vue')['default']
    BViewer: typeof import('./src/components/base/Viewer/BViewer.vue')['default']
    CommonContainer: typeof import('./src/components/base/BasicComponents/CommonContainer.vue')['default']
    FormRenders: typeof import('./src/components/base/BasicComponents/BForm/FormRenders.vue')['default']
    OriginalIcon: typeof import('./src/components/base/SvgIcon/src/OriginalIcon.vue')['default']
    PhoneListMg: typeof import('./src/components/base/phoneComponents/PhoneListMg.vue')['default']
    PhoneMenu: typeof import('./src/components/base/phoneComponents/PhoneMenu/PhoneMenu.vue')['default']
    QrCode: typeof import('./src/components/base/QrCode/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/base/SvgIcon/src/SvgIcon.vue')['default']
    VirtualList: typeof import('./src/components/base/VirtualList/VirtualList.vue')['default']
  }
}
