CREATE TABLE IF NOT EXISTS email_delivery_logs (
  id char(36) NOT NULL,
  email_type varchar(32) NOT NULL COMMENT 'verification/todo_reminder/system',
  user_id varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '关联账号，可为空',
  recipient_email varchar(254) NOT NULL,
  subject varchar(255) NOT NULL,
  business_type varchar(32) DEFAULT NULL COMMENT '关联业务类型',
  business_id varchar(64) DEFAULT NULL COMMENT '关联业务 ID',
  provider varchar(32) NOT NULL DEFAULT 'qq_smtp',
  status varchar(16) NOT NULL DEFAULT 'sending' COMMENT 'sending/accepted/failed',
  attempt_no int NOT NULL DEFAULT 1,
  provider_message_id varchar(255) DEFAULT NULL,
  provider_response varchar(500) DEFAULT NULL,
  error_code varchar(64) DEFAULT NULL,
  error_message varchar(500) DEFAULT NULL,
  accepted_at datetime DEFAULT NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_email_delivery_time (create_time),
  KEY idx_email_delivery_status_time (status, create_time),
  KEY idx_email_delivery_type_time (email_type, create_time),
  KEY idx_email_delivery_user_time (user_id, create_time),
  KEY idx_email_delivery_business (business_type, business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='系统邮件 SMTP 投递记录';
