CREATE TABLE IF NOT EXISTS todo_items (
  id char(36) NOT NULL,
  user_id varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  title varchar(200) NOT NULL,
  description text,
  checklist json DEFAULT NULL,
  priority tinyint NOT NULL DEFAULT 1 COMMENT '0 low / 1 normal / 2 high',
  sort_order bigint NOT NULL DEFAULT 0 COMMENT '用户自定义顺序，值越小越靠前',
  status varchar(16) NOT NULL DEFAULT 'pending' COMMENT 'pending/completed',
  due_at datetime DEFAULT NULL,
  completed_at datetime DEFAULT NULL,
  series_id char(36) DEFAULT NULL COMMENT '重复任务系列 ID；重复提醒不使用此字段',
  recurrence_rule json DEFAULT NULL COMMENT '重复任务规则，与周期提醒相互独立',
  recurrence_instance_at datetime DEFAULT NULL COMMENT '当前重复任务实例时间',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag tinyint NOT NULL DEFAULT 0,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_todo_user_status (user_id, status, del_flag),
  KEY idx_todo_due (user_id, due_at, status, del_flag),
  KEY idx_todo_update (user_id, update_time),
  KEY idx_todo_custom_order (user_id, status, sort_order, id),
  KEY idx_todo_admin_created (del_flag, create_time, user_id(64)),
  UNIQUE KEY uk_todo_series_instance (series_id, recurrence_instance_at),
  CONSTRAINT fk_todo_items_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='待处理中的待办事项';

CREATE TABLE IF NOT EXISTS todo_reminders (
  id char(36) NOT NULL,
  todo_id char(36) NOT NULL,
  user_id varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  channel varchar(16) NOT NULL DEFAULT 'in_app',
  scheduled_at datetime NOT NULL,
  schedule_start_at datetime DEFAULT NULL COMMENT '提醒计划首次执行时间',
  repeat_interval_minutes int DEFAULT NULL COMMENT '周期提醒间隔分钟数，NULL 表示单次',
  repeat_end_at datetime DEFAULT NULL COMMENT '周期提醒结束时间',
  target_email varchar(254) DEFAULT NULL COMMENT '邮件提醒收件地址',
  status varchar(16) NOT NULL DEFAULT 'pending' COMMENT 'pending/processing/sent/failed/cancelled/paused_complete/paused_delete',
  retry_count int NOT NULL DEFAULT 0,
  last_error varchar(500) DEFAULT NULL,
  sent_at datetime DEFAULT NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_todo_reminder (todo_id, channel, scheduled_at),
  KEY idx_todo_reminder_schedule (status, scheduled_at),
  KEY idx_todo_reminder_user (user_id, status),
  CONSTRAINT fk_todo_reminder_todo FOREIGN KEY (todo_id) REFERENCES todo_items(id) ON DELETE CASCADE,
  CONSTRAINT fk_todo_reminder_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='待办站内/邮件提醒计划';
