import express from 'express';
import * as growthHandle from '../router_handle/growthHandle.js';

const router = express.Router();

router.get('/me', growthHandle.getMyGrowth);
router.get('/dashboard', growthHandle.getDashboard);
router.get('/tasks', growthHandle.getGrowthTasksHandle);
router.post('/tasks/claim', growthHandle.claimGrowthTaskHandle);
router.get('/heatmap', growthHandle.getHeatmap);
router.get('/ranks', growthHandle.getRanks);
router.post('/checkin', growthHandle.doCheckin);
router.post('/useProtectCard', growthHandle.doUseProtectCard);
router.get('/weeklyReport', growthHandle.getWeeklyReport);
router.post('/admin/userGrowth', growthHandle.getUserGrowthForAdmin);
router.post('/admin/adjust', growthHandle.doAdminAdjustGrowth);
router.post('/claimDailyBonus', growthHandle.claimDailyBonus);
router.get('/shop', growthHandle.getShop);
router.post('/shop/buy', growthHandle.buyShopItem);
router.get('/inventory', growthHandle.getInventoryHandle);
router.post('/item/use', growthHandle.useItemHandle);
router.post('/equipTitle', growthHandle.equipTitleHandle);
router.post('/equipFrame', growthHandle.equipFrameHandle);
router.get('/lottery', growthHandle.getLottery);
router.post('/lottery/draw', growthHandle.doDrawLottery);
router.post('/achievement/claim', growthHandle.doClaimAchievement);
router.get('/recap', growthHandle.getRecapHandle);
router.get('/claimable', growthHandle.getClaimable);
router.post('/claimAll', growthHandle.doClaimAll);
router.get('/preferences', growthHandle.getPreferences);
router.put('/preferences', growthHandle.putPreferences);
router.post('/recap/state', growthHandle.setRecapState);
router.get('/weekly', growthHandle.getWeekly);
router.post('/weekly/claim', growthHandle.doClaimWeekly);
router.get('/points/log', growthHandle.getMyPointsLog);
router.get('/points/summary', growthHandle.getPointsSummary);
router.put('/preferences/points-goal', growthHandle.putPointsGoal);
router.post('/admin/pointsOverview', growthHandle.getPointsOverviewForAdmin);
router.post('/admin/userPoints', growthHandle.getUserPointsForAdmin);
router.post('/admin/searchUsers', growthHandle.searchUsersForPointsAdmin);
router.post('/admin/grantPoints', growthHandle.doAdminGrantPoints);
router.post('/admin/pointsGovernanceOverview', growthHandle.getPointsGovernanceOverviewForAdmin);
router.post('/admin/pointsGovernanceDailyDetails', growthHandle.getPointsGovernanceDailyDetailsForAdmin);
router.post('/admin/pointsGovernanceSources', growthHandle.getPointsGovernanceSourcesForAdmin);
router.post('/admin/pointsAnomalies', growthHandle.getPointsAnomaliesForAdmin);
router.post('/admin/pointsReconciliation', growthHandle.getPointsReconciliationForAdmin);
router.post('/admin/pointsCorrection', growthHandle.doPointsCorrectionForAdmin);
router.post('/admin/pointsSimulator', growthHandle.simulatePointsPolicyForAdmin);
router.post('/admin/campaigns/list', growthHandle.listPointsCampaignsForAdmin);
router.post('/admin/campaigns/create', growthHandle.createPointsCampaignForAdmin);
router.post('/admin/campaigns/preview', growthHandle.previewPointsCampaignForAdmin);
router.post('/admin/campaigns/freeze', growthHandle.freezePointsCampaignForAdmin);
router.post('/admin/campaigns/confirm', growthHandle.confirmPointsCampaignForAdmin);
router.post('/admin/campaigns/execute', growthHandle.executePointsCampaignForAdmin);
router.post('/admin/campaigns/detail', growthHandle.getPointsCampaignDetailForAdmin);
router.post('/admin/campaigns/delete', growthHandle.deletePointsCampaignForAdmin);
router.post('/notices/read', growthHandle.readNotices);

export default router;
